version: '3.8'

services:
  app:
    container_name: auth
    build: ./
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    depends_on:
      - db
    networks:
      - auth

  db:
    image: postgres:latest
    container_name: db-postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - database_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - auth

volumes:
  database_postgres:

networks:
  auth:
    driver: bridge