version: '3.8'

services:
  app:
    container_name: auth
    build: ./
    env_file:
      - .env
    environment:
      POSTGRES_DSN: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports:
      - 50051:50051
    restart: on-failure
    depends_on:
      - db
    networks:
      - auth

  db:
    image: postgres:latest
    container_name: db-postgres
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./sql/tasks.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - auth

volumes:
  database_postgres:

networks:
  auth:
    driver: bridge